---
title: "B16-IL33 CD4 cells SCRNA-Seq Analysis"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r}
knitr::opts_chunk$set(fig.path = "Graphs/CD4/")
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(dev = c("pdf", "png"))

```

# scRNA Analysis

```{r}
# Packages
library(dplyr)
library(plyr)
library(Seurat)
library(patchwork)
library(readxl)

# Load Data
data_dir <- 'Data/filtered_feature_bc_matrix_1'
load("Data/Cells/tc.Robj")
tc.cd4 <- subset(tc, subset = cellType == "CD4")

immune_genes <- read_excel("Data/ImmuneGenes.xlsx")
immune_genes <- immune_genes[['A2M']]

# Convert Strings
capitalize <- function(x) {
  x <- tolower(x)
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

immune_genes <- capitalize(immune_genes)
immune_genes <- unique(immune_genes)

rm(tc)

```

```{r}
#Feature Selection
tc.cd4 <- FindVariableFeatures(tc.cd4, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(tc.cd4), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(tc.cd4)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2
rm(plot1, plot2, top10)

```

```{r}
#Scale Data
all.genes <- rownames(tc.cd4)
tc.cd4 <- ScaleData(tc.cd4, features = all.genes)

rm(all.genes) #cleanup

```

```{r}
# #Cell Annotation/Clonotype Information
# tcr <- read.csv(paste(data_dir, "all_contig_annotations.csv", sep="/"))
# tcr <- tcr[!duplicated(tcr$barcode), ]
# tcr <- tcr[,c("barcode", "raw_clonotype_id")]
# names(tcr)[names(tcr) == "raw_clonotype_id"] <- "clonotype_id"
# tcr <- filter(tcr, barcode %in% Cells(tc.cd4))
# 
# clonosize <- tcr %>% group_by(tcr["clonotype_id"]) %>% dplyr::summarise(Frequency = n())
# clonosize <- clonosize[!clonosize$clonotype_id=="None",]  # Remove NA
# tcr <- merge(tcr, clonosize, by = "clonotype_id", all = TRUE, sort = FALSE)
# rownames(tcr) <- tcr[,2]
# tcr[,2] <- NULL
# names(tcr)[names(tcr) == "Frequency"] <- "clonosize"
# # tcr <- tcr[!(tcr$clonotype_id=="None"),]  # Remove all 0 clonotype cells
# # tcr[is.na(tcr)] <- 0
# 
# tc.cd4 <- AddMetaData(object=tc.cd4, metadata=tcr)
# 
# rm(tcr, clonosize)
# 
# tc.cd4@meta.data[["clonosize"]][is.na(tc.cd4@meta.data[["clonosize"]])] <- 0

```

```{r}
#Linear Dimensional Reduction
tc.cd4 <- RunPCA(tc.cd4, features = VariableFeatures(object = tc.cd4))
print(tc.cd4[["pca"]], dims = 1:5, nfeatures = 5)
VizDimLoadings(tc.cd4, dims = 1:2, reduction = "pca")
DimPlot(tc.cd4, reduction = "pca") & NoAxes()
DimHeatmap(tc.cd4, dims = 1, cells = 500, balanced = TRUE)
DimHeatmap(tc.cd4, dims = 1:15, cells = 500, balanced = TRUE)

```


```{r}
#Determine dimensionality
tc.cd4 <- JackStraw(tc.cd4, num.replicate = 100)
tc.cd4 <- ScoreJackStraw(tc.cd4, dims = 1:20)
JackStrawPlot(tc.cd4, dims = 1:15)
ElbowPlot(tc.cd4)

```

```{r}
# Dimension reduction UMAP
tc.cd4 <- RunUMAP(tc.cd4, dims = 1:50, umap.method = "umap-learn")
DimPlot(tc.cd4, reduction = "umap", label=TRUE) & NoAxes()

```

```{r}
# Maintain global clustering
tc.cd4$global_clusters <- factor(subset(tc.cd4, subset = cellTypeGene == "CD4-C4-Fosb")$cellTypeGene)
tc.cd4$global_clusters <- revalue(tc.cd4$global_clusters, c("CD4-C4-Fosb"="5"))

```

```{r}
# Cluster cells
tc.cd4 <- FindNeighbors(tc.cd4, dims = 1:50)
tc.cd4 <- FindClusters(tc.cd4, resolution = 1.2)
head(Idents(tc.cd4), 5)

```

```{r}
# Change the information of cells containing global-cluster information
tc.cd4$seurat_clusters <- factor(tc.cd4$seurat_clusters, levels = c(levels(tc.cd4$seurat_clusters), "5"))
tc.cd4$seurat_clusters[Cells(subset(tc.cd4, subset = global_clusters == "5"))] <- tc.cd4$global_clusters[Cells(subset(tc.cd4, subset = global_clusters == "5"))]
Idents(tc.cd4) <- tc.cd4$seurat_clusters

```

```{r}
# Dimension reduction UMAP
tc.cd4@reductions[["umapRNA"]] <- NULL
tc.cd4@reductions[["umap"]] <- NULL

tc.cd4 <- RunUMAP(tc.cd4, dims = 1:50, umap.method = "umap-learn", reduction.name = "umap")
tc.cd4 <- RunUMAP(tc.cd4, dims = 1:50, umap.method = "umap-learn", reduction.name = "umapRNA")

DimPlot(tc.cd4, reduction = "umap", label=TRUE) & NoAxes()

```

```{r}
# Cell Types
VlnPlot(tc.cd4, features = c("Cd4"), slot = "counts", log = TRUE, sort = FALSE, pt.size = 0)
VlnPlot(tc.cd4, features = c("Cd8a"), slot = "counts", log = TRUE, sort = FALSE, pt.size = 0)
VlnPlot(tc.cd4, features = c("Foxp3"), slot = "counts", log = TRUE, sort = FALSE, pt.size = 0)
VlnPlot(tc.cd4, features = c("Il2ra"), slot = "counts", log = TRUE, sort = FALSE, pt.size = 0)

```

```{r}
# find markers for every cluster compared to all remaining cells, report only the positive ones
tc.cd4.markers <- FindAllMarkers(tc.cd4, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
tc.cd4.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_logFC)

top3 <- tc.cd4.markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_logFC)
DoHeatmap(tc.cd4, features = top3$gene) + NoLegend()

top1 <- tc.cd4.markers %>% group_by(cluster) %>% top_n(n = 1, wt = avg_logFC)
DoHeatmap(tc.cd4, features = top1$gene) + NoLegend()

rm(top1, top3)

```

```{r}
# Assign cell type to clusters
new.cluster.ids <- c(0, 1, 2, 3, 4, 5)
new.cluster.ids <- c("CD4-C1-Ccl5", "CD4-C2-Hspa1a", "CD4-C3-Igfbp4", "CD4-C4-Ramp3", "CD4-C5-Il17a", "CD4-C6-Ahnak")
# CD4-Anhak

names(new.cluster.ids) <- levels(tc.cd4)
tc.cd4 <- RenameIdents(tc.cd4, new.cluster.ids)

tc.cd4$cellTypeGene <- Idents(tc.cd4)

Idents(tc.cd4) <- tc.cd4$cellTypeGene


new.cluster.ids <- c("Th1", "ThEa", "ThNaive", "ThEx", "Th17", "ThCyto")

names(new.cluster.ids) <- levels(tc.cd4)
tc.cd4 <- RenameIdents(tc.cd4, new.cluster.ids)

tc.cd4$cd4type <- Idents(tc.cd4)

Idents(tc.cd4) <- tc.cd4$cd4type

tc.cd4$cluster_tumor = as.factor(paste(tc.cd4$cd4type, "_", tc.cd4$tumor))


rm(new.cluster.ids) # Cleanup

```

```{r}
# Cell Types
VlnPlot(tc.cd4, features = c("Cd4"), slot = "counts", log = TRUE, sort = FALSE, pt.size = 0)
VlnPlot(tc.cd4, features = c("Cd8a"), slot = "counts", log = TRUE, sort = FALSE, pt.size = 0)
VlnPlot(tc.cd4, features = c("Foxp3"), slot = "counts", log = TRUE, sort = FALSE, pt.size = 0)
VlnPlot(tc.cd4, features = c("Il2ra"), slot = "counts", log = TRUE, sort = FALSE, pt.size = 0)

```

```{r}
# Dimension reduction UMAP
DimPlot(tc.cd4, reduction = "umap", label=TRUE) & NoAxes()

```

```{r}
# HTO
FeaturePlot(tc.cd4, reduction = "umap", features = c("HTO-1-TotalC", "HTO-2-TotalC", "HTO-3-TotalC", "HTO-4-TotalC"))

# IL33
tumor_list <- ifelse(tc.cd4$HTO_maxID %in% c("HTO-1-TotalC", "HTO-2-TotalC"), "b16", "b16il33")
names(tumor_list) <- colnames(x = tc.cd4)

tc.cd4 <- AddMetaData(object = tc.cd4, metadata = tumor_list, col.name = "tumor") # Add to .metadata

DimPlot(tc.cd4, reduction = "umap", group.by = "tumor") & NoAxes()
DimPlot(tc.cd4, reduction = "umap", group.by = "HTO_maxID") & NoAxes()

rm(tumor_list) #  Cleanup
```

```{r fig.height=5, fig.width = 12}
DimPlot(tc.cd4, reduction = "umap", split.by = "tumor") & NoAxes()
FeaturePlot(tc.cd4, reduction = "umap", features = "clonosize", split.by = "tumor") & NoAxes()

```

# Clonosize Analysis

```{r}
# Visualize clonosize
FeaturePlot(tc.cd4, reduction = "umap", features = "clonosize") & NoAxes()

VlnPlot(tc.cd4, features = "clonosize", sort = FALSE, pt.size = 0)

RidgePlot(tc.cd4, features = "clonosize", sort = FALSE)
VlnPlot(subset(tc.cd4, subset = tumor == "b16"), features = "clonosize", sort = FALSE, pt.size = 0)
VlnPlot(subset(tc.cd4, subset = tumor == "b16il33"), features = "clonosize", sort = FALSE, pt.size = 0)

```

```{r}
# Packages
library(ggplot2)
library(waffle)
library(gridExtra)

clonosize_graphs <- function(group, no_tumor=FALSE, avg_clonosize=FALSE, size="clonosize") {
  if(size=="clonosize"){
    # Clusters
    cluster_distribution <- as.data.frame(table(tc.cd4@meta.data[[group]]))
    cluster_distribution$Label <- sprintf("%s (%s)", cluster_distribution$Var1, scales::percent(round(cluster_distribution$Freq/sum(cluster_distribution$Freq), 2)))
    names(cluster_distribution)[names(cluster_distribution) == "Var1"] <- "cluster"
    
    order <- cluster_distribution$cluster
    cluster_distribution$Label = factor(cluster_distribution$Label, levels = cluster_distribution$Label)
    # Basic piechart
    print(ggplot(cluster_distribution, aes(x="", y=Freq, fill=Label)) +
      ggtitle("All Cells Cluster Distribution") +
      geom_bar(stat="identity", width=1) +
      coord_polar("y", start=0) +
      theme_void())
    
    temp <- as.data.frame.matrix(table(tc.cd4@meta.data[[group]], tc.cd4$tumor))
    names(temp)[names(temp) == "Var1"] <- "cluster"
    names(temp)[names(temp) == "b16"] <- "B16T"
    names(temp)[names(temp) == "b16il33"] <- "B16T_IL33"
    
    temp$cluster <- cluster_distribution$cluster
    
    cluster_distribution <- merge(cluster_distribution, temp, by = "cluster")
    
    cluster_distribution$Label_B16T <- sprintf("%s (%s)", cluster_distribution$cluster, scales::percent(round(cluster_distribution$B16T/sum(cluster_distribution$B16T), 2)))
    
    cluster_distribution$Label_B16T_IL33 <- sprintf("%s (%s)", cluster_distribution$cluster, scales::percent(round(cluster_distribution$B16T_IL33/sum(cluster_distribution$B16T_IL33), 2)))
  
    if (!no_tumor) {
      cluster_distribution = cluster_distribution[match(order, cluster_distribution$cluster),]
      cluster_distribution$Label_B16T = factor(cluster_distribution$Label_B16T, levels = cluster_distribution$Label_B16T)
      #b16
      print(ggplot(cluster_distribution, aes(x="", y=B16T, fill=Label_B16T)) +
        ggtitle("b16 Cells Cluster Distribution") +
        geom_bar(stat="identity", width=1) +
        coord_polar("y", start=0) +
        theme_void())
      cluster_distribution$Label_B16T_IL33 = factor(cluster_distribution$Label_B16T_IL33, levels = cluster_distribution$Label_B16T_IL33)
      #b16 IL33
      print(ggplot(cluster_distribution, aes(x="", y=B16T_IL33, fill=Label_B16T_IL33)) +
        ggtitle("b16 IL33 Cells Cluster Distribution") +
        geom_bar(stat="identity", width=1) +
        coord_polar("y", start=0) +
        theme_void())
    }
  
    rm(temp)
    
    # Tumor
    tumor_distribution <- as.data.frame(table(tc.cd4$tumor, tc.cd4@meta.data[[group]]))
    names(tumor_distribution)[names(tumor_distribution) == "Var1"] <- "tumor"
    names(tumor_distribution)[names(tumor_distribution) == "Var2"] <- "cluster"
    
    if (no_tumor) {fill_color="Cells"} else {fill_color = tumor_distribution$tumor}
    print(ggplot(tumor_distribution, aes(fill=fill_color, y=Freq, x=cluster)) + 
        ggtitle("Tumor Cluster Distribution") + theme_classic() +
        theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
        geom_bar(position="stack", stat="identity"))
    
    if (group!="cellType" & !no_tumor) {
      print(ggplot(tumor_distribution, aes(fill=tumor, y=Freq, x=cluster)) + 
        ggtitle("Tumor Cluster Distribution") + theme_classic() +
        theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
        geom_bar(position="dodge", stat="identity"))
    
      print(ggplot(tumor_distribution, aes(fill=tumor, y=Freq, x=cluster)) + 
        ggtitle("Tumor Cluster Distribution") + theme_classic() +
        theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
        geom_bar(position="fill", stat="identity"))
    }
    
  }
  
  # Clonotypes
  totals <- as.data.frame(table(tc.cd4@meta.data[[group]], tc.cd4@meta.data$orig.ident))
  names(totals)[names(totals) == "Freq"] <- "total"
  names(totals)[names(totals) == "Var1"] <- "cluster"
  totals$Var2 <- NULL
    
  if (avg_clonosize) {
    
  } else {
    for(n in 2:5){
      clonotype_distribution <- as.data.frame(table(tc.cd4@meta.data[[size]]>=n, tc.cd4$tumor, tc.cd4@meta.data[[group]]))
      clonotype_distribution <- clonotype_distribution[!(clonotype_distribution$Var1==FALSE),]
      names(clonotype_distribution)[names(clonotype_distribution) == "Var2"] <- "tumor"
      names(clonotype_distribution)[names(clonotype_distribution) == "Var3"] <- "cluster"
      
      clonotype_distribution <- merge(clonotype_distribution, totals, by="cluster")
      clonotype_distribution <- transform(clonotype_distribution, percent = Freq/total*100)
      
      if (no_tumor) {fill_color="Cells"
      type_graph="stack"} else {fill_color = clonotype_distribution$tumor 
      type_graph="dodge"}
      
      print(ggplot(clonotype_distribution, aes(fill=fill_color, y=Freq, x=cluster)) + 
          ggtitle(paste(size, ">=", n, "Tumor Cluster Distribution")) + theme_classic() +
          theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
          geom_bar(position=type_graph, stat="identity"))
      # print(ggplot(clonotype_distribution, aes(fill=tumor, y=Freq, x=cluster)) + 
      #     ggtitle(paste("Clonosize >=", n, " Tumor Cluster Distribution")) +
      #     theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
      #     geom_bar(position="stack", stat="identity"))
      # 
      # print(ggplot(clonotype_distribution, aes(fill=tumor, y=Freq, x=cluster)) + 
      #   ggtitle(paste("Clonosize >=", n, " Tumor Cluster Distribution")) +
      #   theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
      #   geom_bar(position="fill", stat="identity"))
      if (group!="cellType") {
        print(ggplot(clonotype_distribution, aes(fill=fill_color, y=percent, x=cluster)) + 
          ggtitle(paste(size, ">=", n, "Tumor Cluster Distribution")) + theme_classic() +
          theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
          geom_bar(position=type_graph, stat="identity"))
      }
    }
  }
}

```

```{r}
clonosize_graphs("cd4type")
clonosize_graphs("cellType")
clonosize_graphs("cd4type", no_tumor = TRUE)
# clonosize_graphs("cellTypeGene", avg_clonosize = TRUE)
# clonosize_graphs("cellTypeGene", no_tumor = TRUE, avg_clonosize = TRUE)

plot(density(x = tc.cd4@meta.data$clonosize))

```

```{r}
# Packages
library(plyr)
library(circlize)
library(imager)
library(scales)
library(pheatmap)
library(VennDiagram)
library(knitr)

clonotype_graphs <- function(seurat_object, title, id="clonotype_id") {
  
  colors <- hue_pal()(length(levels(seurat_object@meta.data[["cd4type"]])))
  names(colors) <- levels(seurat_object@meta.data[["cd4type"]])
  
  clonotypes <- as.data.frame.matrix(table(seurat_object@meta.data[[id]], seurat_object$cd4type))
  clonotypes <- clonotypes[, colSums(clonotypes)>0]
  cluster_clonotypes <- read.csv(text="cluster,clonotypes,clonotypes_percent,shared_clonotypes,shared_clonotypes_percent")
  
  for (cluster_name in colnames(clonotypes)){
    shared_clonotypes <- clonotypes[!(clonotypes[,cluster_name]==0),]
    total = table(tc.cd4@meta.data$cd4type, tc.cd4@meta.data$orig.ident)[cluster_name, "tc800"]
    others = subset(shared_clonotypes, select = names(shared_clonotypes) != cluster_name)
    num = sum(shared_clonotypes[cluster_name])
    shared = sum(shared_clonotypes[rowSums(others)>0, ][,cluster_name])
    cluster_clonotypes <- cluster_clonotypes %>% add_row(clonotypes = num, clonotypes_percent = num/total*100, shared_clonotypes = shared, shared_clonotypes_percent = shared/total*100)
  }
  
  cluster_clonotypes$cluster <- colnames(clonotypes)
  
  rm(cluster_name, shared_clonotypes, total, others, num, shared) # Cleanup
  
  max = max(cluster_clonotypes$clonotypes_percent)+5
  print(max)
  
  print(ggplot(cluster_clonotypes, aes(x=clonotypes_percent, y=shared_clonotypes_percent, color=cluster))+
          geom_point(size=5) + theme_classic()+
          xlab("Clonal cells in each cluster (%)") + ylab("Shared clonal cells in each cluster (%)")+
          scale_colour_manual(values = colors)+
          ggtitle(title)+
          coord_fixed(xlim=c(0, max), ylim=c(0, max)))
  
  
  clonotypes <- clonotypes %>% mutate_if(is.numeric, ~1 * (. != 0))
  mat <- crossprod(as.matrix(clonotypes))
  
  # Chord Diagram
  chordDiagram(mat, grid.col = colors, annotationTrack = c("name", "grid"),
    annotationTrackHeight = c(0.1, 0.07))
  chordDiagram(mat, grid.col = colors, scale = TRUE, annotationTrack = c("name", "grid"),
    annotationTrackHeight = c(0.1, 0.07))
  chordDiagram(mat, grid.col = colors, symmetric = TRUE, annotationTrack = c("name", "grid"),
    annotationTrackHeight = c(0.1, 0.07))
  chordDiagram(mat, grid.col = colors, scale = TRUE, symmetric = TRUE, annotationTrack = c("name", "grid"),
    annotationTrackHeight = c(0.1, 0.07))

  
  # Heatmap
  mat <- floor(t(mat * 100 / diag(mat)))
  annotations <- data.frame(Cluster = colnames(mat))
  rownames(annotations) <- colnames(mat)
  
  mat_colors <- as.list(colors)

  pheatmap(mat, border_color = "black",cluster_cols=F, cluster_rows=F,
           cellwidth = 30, cellheight = 30,
           annotation_col = annotations, annotation_row = annotations,
           annotation_colors = mat_colors,
           border=NA, display_numbers = F)
  
}
  
```

```{r fig.width=7, fig.height=7}
clonotype_graphs(subset(tc.cd4, subset = clonosize >= 2), "All CD4 Cells")
clonotype_graphs(subset(tc.cd4, subset = clonosize >= 2 & tumor == "b16"), "All b16 CD4 Cells")
clonotype_graphs(subset(tc.cd4, subset = clonosize >= 2 & tumor == "b16il33"), "All b16il33 CD4 Cells")

```

```{r}
# Averages
cluster.averages <- AverageExpression(subset(tc.cd4, features = immune_genes))
cluster.averages <- as.matrix.data.frame(cluster.averages[["RNA"]])
cluster.averages <- t(scale(t(cluster.averages)))
cluster.averages <- cluster.averages[complete.cases(cluster.averages),]

```

```{r}
# Heatmap
library(RColorBrewer)
library(knitr)

colors <- hue_pal()(length(levels(tc.cd4@meta.data[["cd4type"]])))
names(colors) <- levels(tc.cd4@meta.data[["cd4type"]])

annotations <- data.frame(Cluster = colnames(cluster.averages))
rownames(annotations) <- colnames(cluster.averages)

mat_colors <- as.list(colors)

pheatmap(cluster.averages,
         cellwidth = 30, cellheight = 30,
         annotation_colors = mat_colors,
         annotation_col = annotations,
         border=NA, display_numbers = F,
         filename="Graphs/CD4/heatmap.pdf")

```

```{r}
save(tc.cd4,file="Data/Cells/CD4/tc.cd4.Robj")

```